import { describe, it, expect, beforeAll } from "vitest";
import * as path from "node:path";
import * as fs from "node:fs/promises";
import { parseOpenAPI } from "../src/parser/index";
import {
  getAvailableFormats,
  createEmitter,
  generate,
} from "../src/generator/index";
import type { AgentifyIR } from "../src/types";

const PETSTORE_URL = "https://petstore.swagger.io/v2/swagger.json";

describe("CLI Emitter", () => {
  let ir: AgentifyIR;
  let outputDir: string;

  beforeAll(async () => {
    const result = await parseOpenAPI(PETSTORE_URL);
    ir = result.ir;
    outputDir = path.join(
      process.cwd(),
      "test-output",
      "cli-emitter-" + Date.now(),
    );
  });

  describe("Registry", () => {
    it("includes cli in available formats", () => {
      expect(getAvailableFormats()).toContain("cli");
    });

    it("creates CLIEmitter via factory", () => {
      const emitter = createEmitter("cli");
      expect(emitter.name).toBe("cli");
      expect(emitter.format).toBe("cli");
    });
  });

  describe("Generation", () => {
    let filesWritten: readonly string[];

    beforeAll(async () => {
      const result = await generate(ir, outputDir, ["cli"]);
      expect(result).toHaveLength(1);
      const first = result[0]!;
      expect(first.format).toBe("cli");
      filesWritten = first.filesWritten;
    });

    it("generates 7 files", () => {
      expect(filesWritten).toHaveLength(7);
    });

    it("generates CLI entry point", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "src/cli.ts"),
        "utf-8",
      );
      expect(content).toContain("#!/usr/bin/env node");
      expect(content).toContain('import { Command } from "commander"');
      expect(content).toContain("registerCommands(program)");
      expect(content).toContain("program.parse()");
    });

    it("generates API client with fetch-based requests", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "src/api-client.ts"),
        "utf-8",
      );
      expect(content).toContain("export async function apiRequest");
      expect(content).toContain("await fetch(url, fetchOptions)");
      expect(content).toContain("BASE_URL");
      expect(content).toContain("petstore.swagger.io");
    });

    it("generates commands for all capabilities", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "src/commands.ts"),
        "utf-8",
      );
      expect(content).toContain("export function registerCommands");
      expect(content).toContain(".command(");
      expect(content).toContain(".action(async");
      expect(content).toContain("apiRequest");
      expect(content).toContain("get-pet-by-id");
      expect(content).toContain("add-pet");
    });

    it("uses positional args for path parameters", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "src/commands.ts"),
        "utf-8",
      );
      expect(content).toMatch(/\.command\("get-pet-by-id <petId>"\)/);
    });

    it("uses flags for query/body parameters", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "src/commands.ts"),
        "utf-8",
      );
      expect(content).toMatch(/\.requiredOption\("--status <value>"/);
    });

    it("includes type coercion for numeric flag params", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "src/commands.ts"),
        "utf-8",
      );
      // Integer properties like id, userStatus get Number() coercion
      expect(content).toMatch(/Number\(options\.\w+\)/);
    });

    it("generates valid package.json with commander dependency", async () => {
      const raw = await fs.readFile(
        path.join(outputDir, "package.json"),
        "utf-8",
      );
      const pkg = JSON.parse(raw);
      expect(pkg.name).toContain("cli");
      expect(pkg.bin).toBeDefined();
      expect(pkg.dependencies.commander).toBeDefined();
      expect(pkg.type).toBe("module");
    });

    it("generates .env.example with auth config", async () => {
      const content = await fs.readFile(
        path.join(outputDir, ".env.example"),
        "utf-8",
      );
      expect(content).toContain("SWAGGER_PETSTORE_API_KEY");
      expect(content).toContain("API_BASE_URL");
    });

    it("generates README with command list", async () => {
      const content = await fs.readFile(
        path.join(outputDir, "README.md"),
        "utf-8",
      );
      expect(content).toContain("Petstore");
      expect(content).toContain("## Commands");
      expect(content).toContain("get-pet-by-id");
      expect(content).toContain("Generated by Agentify");
    });

    it("generated code passes security scan", async () => {
      const apiClient = await fs.readFile(
        path.join(outputDir, "src/api-client.ts"),
        "utf-8",
      );
      // Ensure no dangerous patterns in generated code
      expect(apiClient).not.toContain("child_process");
      expect(apiClient).toContain("fetch(url");
    });
  });

  describe("Multi-format generation", () => {
    it("generates CLI alongside other formats", async () => {
      const multiDir = outputDir + "-multi";
      const results = await generate(ir, multiDir, [
        "skills",
        "cli",
        "agents.md",
      ]);
      expect(results).toHaveLength(3);
      const formats = results.map(r => r.format);
      expect(formats).toContain("cli");
      expect(formats).toContain("skills");
      expect(formats).toContain("agents.md");

      const cliTs = await fs.readFile(
        path.join(multiDir, "src/cli.ts"),
        "utf-8",
      );
      expect(cliTs).toContain("Command");

      const skills = await fs.readFile(
        path.join(multiDir, "skills.json"),
        "utf-8",
      );
      expect(JSON.parse(skills).name).toBeDefined();
    });
  });
});
