import * as fs from "node:fs/promises";
import * as path from "node:path";
import type {
  AgentifyIR,
  Capability,
  Domain,
  Emitter,
  EmitterOptions,
  EmitterResult,
} from "../types";

export class CursorRulesEmitter implements Emitter {
  readonly name = "cursorrules";
  readonly format = "cursorrules";

  async emit(ir: AgentifyIR, options: EmitterOptions): Promise<EmitterResult> {
    const outputDir = path.resolve(options.outputDir);
    await fs.mkdir(outputDir, { recursive: true });

    const content = generateCursorRules(ir);
    const filePath = path.join(outputDir, ".cursorrules");
    await fs.writeFile(filePath, content, "utf-8");

    return {
      format: this.format,
      filesWritten: [filePath],
      warnings: [],
    };
  }
}

function generateCursorRules(ir: AgentifyIR): string {
  const sections: string[] = [];

  // Header
  sections.push(`# Project: ${ir.product.name}`);
  sections.push(`# Version: ${ir.product.version}`);
  sections.push(`# Base URL: ${ir.product.baseUrl}`);
  sections.push(`# Generated by Agentify — Agent Interface Compiler`);
  sections.push("");

  // API Context
  sections.push("## API Context");
  sections.push("");
  sections.push(ir.product.description);
  sections.push("");

  // Available Operations
  sections.push("## Available Operations");
  sections.push("");

  for (const domain of ir.domains) {
    const caps = ir.capabilities.filter(c => c.domain === domain.name);
    sections.push(...renderDomainSection(domain, caps));
  }

  // Authentication
  sections.push("## Authentication");
  sections.push("");
  if (ir.auth.type === "none") {
    sections.push("No authentication required.");
  } else {
    sections.push(`This API uses **${ir.auth.type}** authentication.`);
    sections.push("");
    sections.push(`Environment variable: \`${ir.auth.envVariable}\``);
    if (ir.auth.description) {
      sections.push("");
      sections.push(ir.auth.description);
    }
  }
  sections.push("");

  // Code Generation Rules
  sections.push("## Code Generation Rules");
  sections.push("");
  sections.push(`- Base URL: \`${ir.product.baseUrl}\``);
  sections.push("- Use `fetch` or `axios` for HTTP requests");
  sections.push("- Path parameters: replace `{paramName}` in the URL path");
  sections.push("- Query parameters: append as `?key=value` query string");
  sections.push("- Body parameters: send as JSON in the request body with `Content-Type: application/json`");
  if (ir.auth.type !== "none") {
    sections.push(`- Authentication: read \`${ir.auth.envVariable}\` from environment and include in request headers`);
  }

  const sideEffectOps = ir.capabilities.filter(c => c.sideEffects);
  if (sideEffectOps.length > 0) {
    sections.push(`- ${sideEffectOps.length} operations have side effects (POST/PUT/DELETE) — confirm before executing`);
  }
  sections.push("");

  return sections.join("\n");
}

function renderDomainSection(domain: Domain, caps: readonly Capability[]): string[] {
  const lines: string[] = [];

  lines.push(`### ${capitalize(domain.name)}`);
  lines.push("");
  if (domain.description) {
    lines.push(domain.description);
    lines.push("");
  }

  for (const cap of caps) {
    lines.push(`#### ${cap.http.method.toUpperCase()} \`${cap.http.path}\` — ${truncate(cap.description, 100)}`);
    lines.push("");
    if (cap.input.properties.length > 0) {
      for (const p of cap.input.properties) {
        const req = p.required ? "required" : "optional";
        const loc = p.in ?? "body";
        const desc = p.description ? ` — ${p.description}` : "";
        lines.push(`- \`${p.name}\` (${p.type}, ${req}, ${loc})${desc}`);
      }
      lines.push("");
    }
  }

  return lines;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function truncate(str: string, maxLen: number): string {
  return str.length > maxLen ? str.slice(0, maxLen - 3) + "..." : str;
}
