import * as fs from "node:fs/promises";
import * as path from "node:path";
import type {
  AgentifyIR,
  Capability,
  Domain,
  Emitter,
  EmitterOptions,
  EmitterResult,
} from "../types";

export class GeminiMdEmitter implements Emitter {
  readonly name = "gemini-md";
  readonly format = "gemini.md";

  async emit(ir: AgentifyIR, options: EmitterOptions): Promise<EmitterResult> {
    const outputDir = path.resolve(options.outputDir);
    await fs.mkdir(outputDir, { recursive: true });

    const content = generateGeminiMd(ir);
    const filePath = path.join(outputDir, "GEMINI.md");
    await fs.writeFile(filePath, content, "utf-8");

    return {
      format: this.format,
      filesWritten: [filePath],
      warnings: [],
    };
  }
}

function generateGeminiMd(ir: AgentifyIR): string {
  const sections: string[] = [];

  sections.push(`# ${ir.product.name}`);
  sections.push("");
  sections.push(`> Generated by [Agentify](https://github.com/koriyoshi2041/agentify) — Agent Interface Compiler`);
  sections.push("");
  sections.push(ir.product.description);
  sections.push("");

  // API Overview
  sections.push("## API Overview");
  sections.push("");
  sections.push(`- **Base URL:** \`${ir.product.baseUrl}\``);
  sections.push(`- **Version:** ${ir.product.version}`);
  sections.push(`- **Endpoints:** ${ir.capabilities.length}`);
  sections.push(`- **Domains:** ${ir.domains.map(d => d.name).join(", ")}`);
  if (ir.product.docsUrl) {
    sections.push(`- **Documentation:** ${ir.product.docsUrl}`);
  }
  sections.push("");

  // Auth
  if (ir.auth.type !== "none") {
    sections.push("## Authentication");
    sections.push("");
    sections.push(`This API uses **${ir.auth.type}** authentication.`);
    sections.push("");
    sections.push(`Set the \`${ir.auth.envVariable}\` environment variable before making requests.`);
    sections.push("");
    sections.push("```bash");
    sections.push(`export ${ir.auth.envVariable}=your-key-here`);
    sections.push("```");
    sections.push("");
  }

  // Capabilities by domain
  sections.push("## Available Operations");
  sections.push("");

  for (const domain of ir.domains) {
    const caps = ir.capabilities.filter(c => c.domain === domain.name);
    sections.push(...renderDomainSection(domain, caps));
  }

  // Endpoint Reference with parameter details
  sections.push("## Endpoint Reference");
  sections.push("");

  for (const cap of ir.capabilities) {
    sections.push(`### \`${cap.name}\` — ${cap.http.method.toUpperCase()} \`${cap.http.path}\``);
    sections.push("");
    sections.push(cap.description);
    sections.push("");
    if (cap.input.properties.length > 0) {
      sections.push("**Parameters:**");
      sections.push("");
      for (const p of cap.input.properties) {
        const req = p.required ? "required" : "optional";
        const loc = p.in ?? "body";
        const desc = p.description ? ` — ${p.description}` : "";
        sections.push(`- \`${p.name}\` (${p.type}, ${req}, ${loc})${desc}`);
      }
      sections.push("");
    }
  }

  // Gemini CLI Integration
  sections.push("## Gemini CLI Integration");
  sections.push("");
  sections.push("If an MCP server is generated alongside this file, add it to your Gemini CLI config:");
  sections.push("");
  sections.push("```json");
  sections.push(`{`);
  sections.push(`  "mcpServers": {`);
  sections.push(`    "${ir.product.name.toLowerCase().replace(/\\s+/g, "-")}": {`);
  sections.push(`      "command": "npx",`);
  sections.push(`      "args": ["tsx", "src/index.ts"]`);
  sections.push(`    }`);
  sections.push(`  }`);
  sections.push(`}`);
  sections.push("```");
  sections.push("");
  sections.push("Gemini CLI will automatically discover the tools exposed by the MCP server.");
  sections.push("");

  return sections.join("\n");
}

function renderDomainSection(domain: Domain, caps: readonly Capability[]): string[] {
  const lines: string[] = [];

  lines.push(`### ${capitalize(domain.name)}`);
  lines.push("");
  if (domain.description) {
    lines.push(domain.description);
    lines.push("");
  }

  lines.push("| Operation | Method | Path | Description |");
  lines.push("|-----------|--------|------|-------------|");

  for (const cap of caps) {
    const desc = truncate(cap.description, 80);
    lines.push(`| \`${cap.name}\` | ${cap.http.method.toUpperCase()} | \`${cap.http.path}\` | ${desc} |`);
  }

  lines.push("");
  return lines;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function truncate(str: string, maxLen: number): string {
  return str.length > maxLen ? str.slice(0, maxLen - 3) + "..." : str;
}
